---
title: "Project 1"
author: "Miriam Hu, Syaza Senin, Eungkoo (Eugene) Kahng, Youngihn Kwon"
date: "October 6, 2017"
output:
  html_document: default
---


```{r, include=FALSE}
library(knitr)
library(tidyverse)
opts_chunk$set(echo=FALSE,
               cache=TRUE, autodep=TRUE,
               message=FALSE, warning=FALSE)
```


## Question 1

```{r data-loading, include=FALSE}
# I need to set setwd otherwise it cause error, you guys can change it
# setwd("C:\\Users\\Asus\\Desktop\\2017 Fall\\STAT-S 470\\Small Projects\\Small Project 1")
methane <- read.csv("COP_CH4_Obs_Mod_Bg_Sep2012-Aug2013.csv")

afternoon <- c("16", "17", "18", "19", "20", "21")
spring.months <- c("3", "4", "5")
spring <- methane %>% filter(Mn %in% spring.months & Hr %in% afternoon)
summer.months <- c("6", "7", "8")
summer <- methane %>% filter(Mn %in% summer.months & Hr %in% afternoon)
fall.months <- c("9", "10", "11")
fall <- methane %>% filter(Mn %in% fall.months & Hr %in% afternoon)
winter.months <- c("12", "1", "2")
winter <- methane %>% filter(Mn %in% winter.months & Hr %in% afternoon)

# For part i)
season.dat <- rbind(spring, summer, fall, winter)
Season <- c(rep("spring",nrow(spring)), rep("summer",nrow(summer)),
            rep("fall",nrow(fall)), rep("winter",nrow(winter)))
season.noon <- cbind(Season, season.dat)

# For part ii)
methane$Date <- as.Date(with(methane, paste(Yr, Mn, Dy, sep="-")), "%Y-%m-%d")
CH4.ave <- ddply(methane, .(Date), summarize, daily.ave = mean(Obs))
```

```{r density-plot, fig.align="center"}
ggplot(season.noon, aes(x = Obs, colour = Season)) + geom_density() + 
  ggtitle("CH4 Observations Distribution by Season") + 
  xlab("CH4 Observations") + ylab("Probability")
```

```{r time-series, fig.align="center"}
# I don't know what it meant by "fit a trend component"
ggplot(methane, aes(Date, CH4.ave[2])) + geom_line() + ylab("Daily CH4 Average") +
  ggtitle("Daily CH4 Average")
```


## Question 2

```{r model-fitting, fig.align="center"}
methane.bu.sp <- read.csv("BU C2H6 CH4 5min May-Jun2014.csv")
methane.bu.fa <- read.csv("BU C2H6 CH4 5min Oct2012-Jan2013.csv")
```